const { v4: uuidv4 } = require("uuid");
const { getPool } = require("../config/database");
function getPath(obj,path){return path.split(".").reduce((v,k)=>v==null?undefined:v[k],obj)}
function setPath(obj,path,value){const keys=path.split(".");let cur=obj;keys.forEach((k,i)=>{if(i===keys.length-1)cur[k]=value;else cur=cur[k]||(cur[k]={})})}
function clone(v){if(v==null||typeof v!=="object")return v;if(v instanceof Date)return new Date(v.getTime());if(Array.isArray(v))return v.map(clone);const out={};for(const[k,val]of Object.entries(v)){if(k!=="toObject")out[k]=clone(val)}return out}
function decorate(v){if(!v||typeof v!=="object")return v;if(Array.isArray(v)){v.forEach(decorate);return v}Object.keys(v).forEach(k=>decorate(v[k]));if(!Object.prototype.hasOwnProperty.call(v,"toObject"))Object.defineProperty(v,"toObject",{enumerable:false,value:()=>clone(v)});return v}
function equal(a,b){return String(a)===String(b)}
function matchesValue(actual,expected){if(expected&&typeof expected==="object"&&!Array.isArray(expected)){if("$in"in expected)return expected.$in.some(x=>equal(actual,x));if("$nin"in expected)return!expected.$nin.some(x=>equal(actual,x));if("$ne"in expected)return!equal(actual,expected.$ne);if("$exists"in expected)return expected.$exists?actual!==undefined:actual===undefined;if("$gte"in expected)return actual>=expected.$gte;if("$gt"in expected)return actual>expected.$gt;if("$lte"in expected)return actual<=expected.$lte;if("$lt"in expected)return actual<expected.$lt}if(Array.isArray(actual))return actual.some(x=>equal(x,expected));return equal(actual,expected)}
function matches(doc,filter={}){return Object.entries(filter).every(([k,e])=>k==="$or"?e.some(f=>matches(doc,f)):k==="$and"?e.every(f=>matches(doc,f)):matchesValue(getPath(doc,k),e))}
function applyUpdate(doc,update){Object.assign(doc,Object.fromEntries(Object.entries(update).filter(([k])=>!k.startsWith("$"))));if(update.$set)for(const[k,v]of Object.entries(update.$set))setPath(doc,k,v);if(update.$unset)for(const k of Object.keys(update.$unset)){const p=k.split("."),last=p.pop(),parent=getPath(doc,p.join("."));if(parent)delete parent[last]}if(update.$inc)for(const[k,v]of Object.entries(update.$inc))setPath(doc,k,Number(getPath(doc,k)||0)+Number(v));if(update.$push)for(const[k,v]of Object.entries(update.$push)){const a=getPath(doc,k);if(Array.isArray(a))a.push(v);else setPath(doc,k,[v])}if(update.$addToSet)for(const[k,v]of Object.entries(update.$addToSet)){const a=getPath(doc,k);if(Array.isArray(a)&&!a.some(x=>JSON.stringify(x)===JSON.stringify(v)))a.push(v);else if(!a)setPath(doc,k,[v])}return doc}
class Query{constructor(Model,filter,single=false){this.Model=Model;this.filter=filter||{};this.single=single;this.opts={}}select(v){this.opts.select=v;return this}sort(v){this.opts.sort=v;return this}skip(v){this.opts.skip=Number(v)||0;return this}limit(v){this.opts.limit=Number(v)||0;return this}populate(path,select){(this.opts.populate||(this.opts.populate=[])).push({path,select});return this}async exec(){let rows=(await this.Model._all()).filter(x=>matches(x,this.filter));if(this.opts.sort){const[field,dir]=Object.entries(this.opts.sort)[0];rows.sort((a,b)=>(getPath(a,field)>getPath(b,field)?1:getPath(a,field)<getPath(b,field)?-1:0)*Number(dir||1))}if(this.opts.skip)rows=rows.slice(this.opts.skip);if(this.opts.limit)rows=rows.slice(0,this.opts.limit);rows=await Promise.all(rows.map(x=>this.Model._hydrate(x,this.opts)));return this.single?(rows[0]||null):rows}then(r,j){return this.exec().then(r,j)}catch(j){return this.exec().catch(j)}}
class UpdateQuery{constructor(Model,id,update,options){this.Model=Model;this.id=id;this.update=update;this.options=options||{};this.opts={}}select(v){this.opts.select=v;return this}populate(path,select){(this.opts.populate||(this.opts.populate=[])).push({path,select});return this}async exec(){const obj=await this.Model.findById(this.id);if(!obj)return null;applyUpdate(obj,this.update);await obj.save();return this.Model._hydrate(obj,this.opts)}then(r,j){return this.exec().then(r,j)}catch(j){return this.exec().catch(j)}}
class MysqlModel{static collection="documents";constructor(data={}){Object.assign(this,clone(data));if(!this._id)this._id=uuidv4();const now=new Date();this.createdAt||=now;this.updatedAt||=now;decorate(this)}static _raw(row){if(!row)return null;const parsed=typeof row.data==="string"?JSON.parse(row.data):row.data;return{...parsed,_id:row.id,createdAt:row.created_at,updatedAt:row.updated_at}}static async _all(){const[rows]=await getPool().query("SELECT id,data,created_at,updated_at FROM app_documents WHERE collection=?",[this.collection]);return rows.map(r=>this._raw(r))}static async _hydrate(data,opts={}){const obj=new this(data);if(this.collection==="users"&&opts.select!=="+passwordHash"&&(!opts.select||!opts.select.includes("+passwordHash")))delete obj.passwordHash;if(opts.select&&opts.select.startsWith("-"))delete obj[opts.select.slice(1)];if(opts.populate)for(const p of opts.populate)await this._populate(obj,p);return obj}static async _populate(obj,{path}){const ref=obj[path],map={userId:"users",assignedTo:"users",reviewedBy:"users",issuedBy:"users",revokedBy:"users"},Model=MODEL_REGISTRY[map[path]];if(!ref||!Model)return;if(Array.isArray(ref))obj[path]=await Promise.all(ref.map(id=>Model.findById(id)));else obj[path]=await Model.findById(ref)}static find(f={}){return new Query(this,f)}static findOne(f={}){return new Query(this,f,true)}static findById(id){return new Query(this,{_id:id},true)}static findByIdAndUpdate(id,u,o={}){return new UpdateQuery(this,id,u,o)}static async create(d){const o=new this(d);await o.save();return o}static async countDocuments(f={}){return(await this._all()).filter(x=>matches(x,f)).length}static async aggregate(p=[]){let rows=await this._all();for(const s of p){if(s.$match)rows=rows.filter(x=>matches(x,s.$match));if(s.$group){const g=new Map(),idPath=String(s.$group._id||"").replace(/^\$/,'');for(const r of rows){const k=getPath(r,idPath);g.set(String(k),{_id:k,count:(g.get(String(k))?.count||0)+1})}rows=[...g.values()]}}return rows}static async deleteMany(f={}){const rows=(await this._all()).filter(x=>matches(x,f));for(const x of rows)await new this(x).deleteOne();return{deletedCount:rows.length}}async save(){this.updatedAt=new Date();const data=clone(this);await getPool().execute("INSERT INTO app_documents (id,collection,data,created_at,updated_at) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE data=VALUES(data),updated_at=VALUES(updated_at)",[this._id,this.constructor.collection,JSON.stringify(data),this.createdAt,this.updatedAt]);return this}async deleteOne(){await getPool().execute("DELETE FROM app_documents WHERE id=? AND collection=?",[this._id,this.constructor.collection])}toJSON(){return clone(this)}}
const MODEL_REGISTRY={};function registerModel(collection,Model){MODEL_REGISTRY[collection]=Model;Model.collection=collection;return Model}
module.exports={MysqlModel,Query,registerModel,decorate,applyUpdate,getPath,setPath};
